/* Every numeric value that appears in the Class 4 source material, by topic.
   CDG = Commercial Driver's Guide (Spring 2025). DG = Driver's Guide: Cars and Light Trucks (Spring 2026). */
window.NUMBERS = [
 {g:"The test itself", rows:[
  ["Questions on the knowledge test","30 multiple choice","CDG 13"],
  ["Correct answers needed to pass","25 of 30","CDG 13"],
  ["Wrong answers that end the test","6 — test stops, fail recorded","CDG 13"],
  ["Attempts per day","1","alberta.ca"],
 ]},
 {g:"Class 4 licence", rows:[
  ["Minimum learning / licensing age","18 years","CDG 11"],
  ["Bus seating capacity allowed","not more than 24, excluding the operator","CDG 11"],
  ["Licence needed before learning commercial","Class 5 or Class 5 GDL","CDG 13"],
  ["Licence needed for a commercial road test","full Class 5, non-GDL","CDG 14"],
  ["Re-class waiting period, other Canadian jurisdictions","10 days","CDG 13"],
  ["Class 2 road test bus","seating over 24, excluding the driver","CDG 15"],
  ["Bus, by definition","designed for 11+ persons including the driver","CDG 9"],
  ["Intercity bus, by definition","more than 15 passengers including the driver","CDG 9"],
  ["Class 5 seating ceiling when carrying others","15","DG 14"],
 ]},
 {g:"Medical and vision", rows:[
  ["Medical report required for classes","1, 2 and 4","CDG 14"],
  ["Medical interval until age 45","every 5 years","CDG 14"],
  ["Medical interval, 45 to 65","every 3 years","CDG 14"],
  ["Medical interval, after 65","every year","CDG 14"],
  ["Driver Medical Intake Form and vision check to apply for or renew Class 7, 6, 5 or 3","age 75 or older","DG 17"],
 ]},
 {g:"Hours of service — Alberta", rows:[
  ["Off-duty period that starts a work shift","8 consecutive hours","CDG 21"],
  ["Maximum driving in a work shift","13 hours","CDG 21"],
  ["Maximum on-duty in a work shift","15 hours","CDG 21"],
  ["Daily log delivered to employer within","20 days","CDG 21"],
  ["Driver keeps a copy of each log","at least 6 months","CDG 21"],
  ["Log exemption radius","160 km of the home terminal","CDG 21"],
  ["Log exemption — hours from start to relieved of duty","no more than 15","CDG 21"],
  ["Personal use of a commercial vehicle","up to 75 km per day","CDG 97"],
 ]},
 {g:"Hours of service — federal", rows:[
  ["Maximum driving in a day","13 hours","CDG 22"],
  ["Maximum on-duty in a day","14 hours","CDG 22"],
  ["Off-duty per day","10 hours — 8 consecutive, the other 2 in blocks of 30 min or more","CDG 22"],
  ["Elapsed-time limit in a work shift","16 hours since the last 8 consecutive off","CDG 22"],
  ["Cycle 1","70 on-duty hours in 7 consecutive days","CDG 22"],
  ["Cycle 2","120 on-duty hours in 14 consecutive days","CDG 22"],
  ["Cycle 1 reset","36 consecutive hours off","CDG 22"],
  ["Cycle 2 reset","72 consecutive hours off","CDG 22"],
  ["Cycle 2 — hours off before the 70th on-duty hour","24 consecutive","CDG 22"],
  ["Minimum off in the preceding 14 days","24 consecutive hours","CDG 22"],
  ["Federal log exemption radius","160 km of the home terminal","CDG 22"],
 ]},
 {g:"Weights and thresholds", roclass:"", rows:[
  ["Safety Fitness Certificate — federal, trucks","over 4,500 kg","CDG 19"],
  ["Safety Fitness Certificate — provincial, trucks","11,794 kg or greater","CDG 19"],
  ["Safety Fitness Certificate — passenger vehicles","seating 11+ including the driver","CDG 19"],
  ["Trip inspection report — provincial carriers","trucks 11,794 kg and greater","CDG 26"],
  ["Trip inspection report — federal carriers","trucks 4,500 kg and greater","CDG 26"],
  ["Trip inspection report — passenger vehicles","seating 11+ including the driver","CDG 26"],
  ["Cargo securement applies to trucks over","4,500 kg","CDG 24"],
  ["Must report to an inspection station","commercial vehicles over 4,500 kg, when the lights flash","CDG 38"],
  ["Trailer requiring driver-controlled brakes","over 2,300 kg","CDG 60"],
 ]},
 {g:"Vehicle Inspection Program", rows:[
  ["Buses — inspection interval","every 6 months","CDG 23"],
  ["Trucks and trailers — inspection interval","every 12 months","CDG 23"],
  ["Buses that must be inspected","designed to carry 11+ passengers including the driver","CDG 23"],
  ["Trucks and trailers that must be inspected","registered combined GVW 11,794 kg or more","CDG 23"],
  ["Exempt when operating solely in Alberta","municipal transit buses, farm trucks","CDG 23"],
 ]},
 {g:"Trip inspections", rows:[
  ["Inspection and report valid for","a maximum of 24 hours","CDG 26–27"],
  ["Major defect — reported","without delay","CDG 29"],
  ["Minor defect — reported","by the next required daily trip inspection","CDG 29"],
  ["Brake pedal held under moderate force","10 seconds","CDG 51"],
  ["Maximum brake pedal travel under heavy force","80% of total available travel","CDG 51"],
  ["Minimum tyre tread depth","1.6 mm","CDG 34–35"],
  ["Minimum parking brake friction material","1.6 mm","CDG 49"],
  ["Maximum chip or crack in the wiper-swept area","25 mm diameter","CDG 48"],
  ["Minimum exhaust clearance to wiring, fuel, brakes or combustibles","50 mm","CDG 50"],
 ]},
 {g:"Vehicle dimensions", rows:[
  ["Maximum width","2.6 m","CDG 56"],
  ["Width above which clearance lights are required","2.05 m — amber front, red rear","CDG 56"],
  ["Maximum height from the ground","4.15 m","CDG 56"],
  ["Maximum length, straight truck or bus","12.5 m","CDG 56"],
  ["Maximum length, intercity bus","14 m","CDG 56"],
  ["Maximum wheelbase, truck-tractor","6.2 m","CDG 56"],
  ["Maximum overall length, tractor semi-trailer","23 m","CDG 56"],
  ["Maximum overall length, TAC A/B/C trains","25 m","CDG 56"],
 ]},
 {g:"Stopping and following", rows:[
  ["Average perception time","about 3/4 second","CDG 59"],
  ["Average reaction time","about 3/4 second","CDG 59"],
  ["Air brake lag time","about 4/10 second","CDG 59"],
  ["Following distance — passenger vehicle","2 seconds minimum","CDG 63"],
  ["Following distance — large vehicle","4 seconds","CDG 63"],
  ["Poor weather, road or traffic","double the following distance","CDG 64"],
  ["Double the weight","about twice the stopping time","CDG 58"],
  ["Double the speed","4× the braking force","CDG 58"],
  ["Double speed and weight","about 8× the force","CDG 58"],
  ["Stopping distance at 70 km/h","about 90 m (300 ft)","CDG 140"],
  ["Mirrors should show behind the vehicle","60 m, or four vehicle-lengths","CDG 62"],
  ["Blind spot from the rear bumper","up to 100 m or more","CDG 65"],
  ["66-passenger bus at 45 kg per passenger","3,000 kg over the vehicle's own weight","CDG 59"],
 ]},
 {g:"Railway crossings", rows:[
  ["Stop no closer than","5 m (16 ft) from the nearest rail","CDG 93"],
  ["At a stop sign, stop between","5 m and 15 m from the nearest rail","CDG 93"],
  ["Train in sight within this distance — must stop","500 m","CDG 93"],
  ["No parking near a controlled crossing, outside urban areas","within 50 m (164 ft) of the nearest rail","CDG 93"],
  ["A train overhangs the rails by","about 1 m on both sides","CDG 93"],
  ["Shifting gears while crossing","prohibited","CDG 93"],
 ]},
 {g:"Buses and turnarounds", rows:[
  ["Parallel parking — drive forward past the lane","1.5 × total unit length","CDG 92"],
  ["Passenger-side turnaround — pull ahead","about one bus-length, 1 to 1.5 m from the side","CDG 89"],
  ["Driver-side turnaround — signal left at","about 100 m","CDG 89"],
  ["Horn while reversing a bus","once for every bus-length","CDG 89"],
  ["U-turn near a crest or curve — must be visible within","150 m (492 ft) from either direction","CDG 90"],
  ["Stopping for a school bus with red lights flashing","about 20 m (four to five car lengths)","DG 101"],
  ["Snowplough pulls over to let traffic pass every","5 to 8 km","DG 102"],
 ]},
 {g:"Passengers", rows:[
  ["Driver must restrain passengers under","16 years of age","CDG 117"],
  ["Car seat required below","18 kg (40 lb)","CDG 117"],
  ["Watch ahead when pushing a wheelchair","at least 3 m (10 ft)","CDG 118"],
 ]},
 {g:"Emergencies", rows:[
  ["Move passengers from a bus fire at least","35 m (115 ft) away","CDG 124"],
  ["Fire extinguisher discharge","8 to 10 seconds","CDG 124"],
  ["Warning devices, daylight, outside urban limits","about 30 m (100 ft) front and rear","CDG 125"],
  ["Warning devices, darkness or visibility under 150 m","75 m (250 ft) front and rear","CDG 125"],
  ["A stopped bus should be visible for","300 m or more","CDG 131"],
  ["Collision must be reported if damage exceeds","$5,000","CDG 130"],
  ["Two-vehicle collisions occurring at intersections","about half","CDG 129"],
 ]},
 {g:"Fuel", rows:[
  ["Propane — ignition sources kept away","3 m (10 ft)","CDG 136"],
  ["Propane tank filled to","about 80% of capacity","CDG 136"],
  ["Idling at 900 rpm burns","up to 4 litres per hour","CDG 139"],
  ["Idling that costs more than a restart","10 seconds","CDG 139"],
  ["Fuel wasted per 10 psi of under-inflation","1%","CDG 138"],
  ["Snow-covered roads add","15 to 20% fuel consumption","CDG 137"],
  ["Every 10 km/h over 90 km/h adds","10% more fuel","CDG 139"],
  ["Check gauges, tyres and cargo every","3 hours","CDG 138"],
  ["Adequate warm-up idle","5 minutes","CDG 138"],
  ["10% less aerodynamic drag gives","5% better fuel efficiency","CDG 137"],
  ["Progressive shifting at","about 1600 rpm (downshift about 1200)","CDG 139–141"],
 ]},
 {g:"Zones and speed", rows:[
  ["Provincial highway outside an urban area","100 km/h unless otherwise posted","DG 27"],
  ["Provincial highway inside a city's corporate limit","80 km/h unless otherwise posted","DG 27"],
  ["Roadway outside an urban area (not a provincial highway)","80 km/h unless otherwise posted","DG 27"],
  ["Roadway within an urban area","50 km/h unless otherwise posted","DG 27"],
  ["Slow-moving vehicle sign is used below","40 km/h","DG 37"],
  ["Construction zone fines when workers are present","doubled","DG 37"],
  ["School zone speed, urban and rural","30 km/h unless otherwise posted","DG 30"],
  ["School zone hours","school days: 8:00–9:30, 11:30–13:30, 15:00–16:30","DG 30"],
  ["Playground zone speed","30 km/h unless otherwise posted","DG 31"],
  ["Playground zone hours","every day, 8:30 a.m. to one hour after sunset","DG 31"],
  ["Passing inside a school or playground zone in effect","not permitted","DG 30–31"],
 ]},
 {g:"Parking distances", rows:[
  ["Parked wheels from the curb","no more than 50 cm","DG 52"],
  ["Angle parking — front wheel to curb","light contact, or within 50 cm (20 in)","DG 53"],
  ["Perpendicular parking — space from the vehicle to your right","about 2 m (6 ft)","DG 54"],
  ["Angle parking — distance from the parked vehicle's rear","about 1.5 m (5 ft)","DG 53"],
  ["No parking from a stop or yield sign","within 5 m (16 ft)","DG 55–56"],
  ["No parking from a marked crosswalk","within 5 m","DG 56"],
  ["No parking from a fire hydrant","within 5 m","DG 56"],
  ["No parking from a garage or driveway access","within 1.5 m (5 ft)","DG 55"],
  ["No parking from the edge of an intersecting roadway","closer than 5 m","DG 56"],
  ["Outside an urban area, vehicle must be visible for","60 m (200 ft) in both directions","DG 56"],
 ]},
 {g:"Demerit points", rows:[
  ["Failing to remain at the scene of a collision","7","DG 109"],
  ["Careless driving; failing to stop for a school bus; racing; 51+ km/h over","6","DG 109"],
  ["Failing to stop for a peace officer; failing to stop at a railway crossing (school bus / dangerous cargo)","5","DG 109"],
  ["Failing to yield to a pedestrian in a crosswalk; following too closely; 31–50 km/h over","4","DG 109"],
  ["Red light; stop sign; improper passing; stunting; 16–30 km/h over","3","DG 109"],
  ["Improper turns; U-turn; lane violation; improper backing; up to 15 km/h over","2","DG 109"],
  ["Listed distracted-driving offences (hand-held phone, texting, GPS entry, grooming…)","3, plus a fine","DG 90"],
 ]},
 {g:"Demerit suspensions", rows:[
  ["Warning letter — fully licensed","8 to 14 points in 2 years","DG 108"],
  ["Automatic suspension — fully licensed","15 or more points in 2 years","DG 108"],
  ["Warning letter — GDL","4 to 7 points in 2 years","DG 108"],
  ["Automatic suspension — GDL","8 or more points in 2 years","DG 108"],
  ["Points remaining after reinstatement — fully licensed","7","DG 108"],
  ["Points remaining after reinstatement — GDL","3","DG 108"],
  ["First suspension","1 month","DG 110"],
  ["Second within one year","3 months","DG 110"],
  ["Third within two years","6 months","DG 110"],
  ["Points come off the record","2 years from the conviction","DG 110"],
  ["Convictions stay on the record","10 years","DG 108"],
  ["Approved defensive driving course credit","3 points, for 2 years","DG 110"],
 ]},
 {g:"Impaired driving — IRS", rows:[
  ["IRS: WARN threshold","50 mg alcohol in 100 mL blood","DG 112"],
  ["IRS: FAIL threshold","80 mg alcohol in 100 mL blood","DG 113"],
  ["IRS ZERO: Commercial","zero tolerance, any alcohol or drug","DG 112"],
  ["IRS ZERO: Commercial — 1st / 2nd / 3rd","3 days $300 / 15 days $600 / 30 days $1,200","DG 112"],
  ["IRS ZERO: Novice","30-day suspension, 7-day seizure, $200 fine","DG 112"],
  ["IRS: WARN — 1st","3-day suspension, 3-day seizure, $300","DG 112"],
  ["IRS: WARN — 2nd","15-day suspension, 7-day seizure, Crossroads course, $600","DG 112"],
  ["IRS: WARN — 3rd","30-day suspension, 7-day seizure, IMPACT program, $1,200","DG 112"],
  ["IRS: FAIL — 1st","90 days, then 12 months; 30-day seizure; $1,000","DG 113"],
  ["IRS: FAIL — 2nd","90 days, then 36 months; 30-day seizure; $2,000","DG 114"],
  ["IRS: FAIL — 3rd","90 days, then lifetime; 30-day seizure; $2,000","DG 114"],
  ["IRS: FAIL — Planning Ahead course deadline","450 days","DG 113"],
  ["IRS: FAIL — IMPACT program deadline","1,170 days","DG 114"],
  ["Lifetime suspension — earliest application to reinstate","after 10 years","DG 114"],
  ["Victim fine surcharge","20%","DG 112"],
 ]},
 {g:"Criminal Code disqualifications", rows:[
  ["Impaired driving, no prior offence","1 year","DG 111"],
  ["One prior offence in the last 10 years","3 years","DG 111"],
  ["Two or more prior offences in the last 10 years","5 years","DG 111"],
  ["Death or injury caused","minimum 5 years, even a first offender","DG 111"],
  ["Driving while suspended — vehicle seizure","30 days","DG 115"],
 ]},
 {g:"Residency and visitors", rows:[
  ["Visitors may drive on an out-of-province licence for","up to 1 year","DG 16"],
  ["New residents from elsewhere in Canada","first 90 days","DG 16"],
 ]}
];
